"""
Run the general solver routine blackbox.solve(...), which is designed to
handle an arbitrary matrix.
"""

import numpy as np
import pyamg

# Run solve(...) with the verbose option
n = 100
A = pyamg.gallery.poisson((n, n),format='csr')
b = np.array(np.arange(A.shape[0]), dtype=float)
x = pyamg.solve(A,b,verb=True)

# Return the solver generated by solve(...) so that it can be used again
(x, ml) = pyamg.solve(A, b, verb=False, return_solver=True, tol=1e-8)

# run for a new right-hand-side
b2 = np.random.rand(b.shape[0])
x2 = pyamg.solve(A, b2, verb=False, existing_solver=ml, tol=1e-8)
